config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf.urls import url

urlpatterns = [
    path("", include('consalt.reports.urls', namespace='reports')),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("consalt.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

consalt/reports/urls.py
from django.conf.urls import url
from . import views
from django.urls import include, path
from django.views.generic import TemplateView

app_name = "reports"
urlpatterns = [
    path("", views.HomePageView.as_view(), name='home'),
    path(
        "thank-you/",
        TemplateView.as_view(template_name="pages/thank_you.html"),
        name="thank_you",
    ),

]

consalt/users/urls.py
from django.urls import path

from consalt.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

consalt/reports/models.py
from django.db import models
from django.core.mail import send_mail
from django.conf import settings
import pdb

class Report(models.Model):
    store_name = models.CharField(max_length= 256)
    created_ad = models.DateTimeField(auto_now_add=True,blank=False, null= False)
    date = models.DateField(blank=False, null=False)
    turn = models.IntegerField(blank=False, null=False)
    period = models.FloatField(blank=False, null=False)
    sold = models.IntegerField(blank=False, null=False)
    fuels = models.IntegerField(blank=False, null=False)






    def __str__(self):
        return 'name: {0},  created ad: {1}'.format(self.store_name, self.created_ad)


    def send_email(self):
        date = str(self.date)
        created_date = self.created_ad.strftime('%d %m %Y')
        subject = 'Report {0} date {1}'.format(self.store_name, date)
        message = 'Store Name:  {} \
                   Created Date:  {} \
                   Date:  {} \
                   Turn:  {} \
                   Period:  {} \
                   Sold:  {} \
                   Fuels:  {}'.format(self.store_name, created_date, self.date, self.turn, self.period, self.sold, self.fuels)
        email_from = settings.EMAIL_HOST_USER
        recipient_list = ['Andriy592@gmail.com', ]
        send_mail(subject, message, email_from, recipient_list)

consalt/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

consalt/reports/forms.py
from django import forms
from .models import Report


class ReportForm(forms.ModelForm):

    def send_email(self):
        # TODO send email using the self.cleaned_data dictionary
        pass

    class Meta:
        model = Report
        fields = ('store_name', 'date', 'turn', 'period', 'sold', 'fuels')

consalt/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

consalt/reports/views.py
from django.shortcuts import render
from .forms import ReportForm
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .models import Report
import pdb


class HomePageView(FormView):
    template_name = 'pages/home_page.html'
    form_class = ReportForm
    success_url = reverse_lazy('reports:thank_you')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        report = Report.objects.create(store_name=form.cleaned_data['store_name'], date=form.cleaned_data['date'], turn=form.cleaned_data['turn'], period=form.cleaned_data['period'],
                                       sold=form.cleaned_data['sold'], fuels=form.cleaned_data['fuels'])
        report.send_email()
        return super().form_valid(form)




# class HomePageViews(TemplateView):
#     template_name = 'pages/home_page.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(HomePageViews, self).get_context_data(**kwargs)
#         context.update({
#             'form': ReportForm(),
#
#         })
#         return context
#
#     def post(self,request):
#         if request.method == 'POST':
#             pdb.set_trace()
#             form = ReportForm(request.POST)
#             if form.is_valid():
#                 cd = form.cleaned_data
#                 self.send_email(cd['store_name'], cd['date'])
#         else:
#             form = ReportForm()
#
#         return render(request, 'pages/home_page.html', {'form': form})
#
#     def send_email(self, store_name, date):
#         str(date)
#         formatted_date = date.stfrtime('%d %B, %Y')
#         subject = 'Report {0} date {1}'.format(store_name, formatted_date)
#         message = ' it  means a world to us '
#         email_from = settings.EMAIL_HOST_USER
#         recipient_list = ['receiver@gmail.com', ]
#         send_mail(subject, message, email_from, recipient_list)
#         return redirect('redirect to a new page')

consalt/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

consalt/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

consalt/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Consaltio and Auditio{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'reports:home' %}">Consaltio and Auditio</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'reports:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}

      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Required by Bootstrap v4.1.1 -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 